Repository part4-10teamProject/epigram, pull requests merged in 2024-08, with the labels that each got.

#8 T1 16 feat/popup modal(프로필 모달과 삭제하기 모달)
  .env
  .gitignore
  public/assets/images/close.png
  public/assets/images/exclamation_mark.png
  public/assets/images/profile_sample.png
  src/api/AxiosInstance.tsx
  src/app/layout.tsx
  src/components/common/Comment.tsx
  src/components/common/Modal.tsx
  src/components/common/ProfileModal.tsx
  src/components/common/SearchText.tsx
  src/types/modal.ts
  src/types/profileModal.ts
Labels: 🍀feat

#9 T1 10 header navigation bar
  public/assets/icons/default_user.svg
  public/assets/icons/gnb_menu.svg
  public/assets/icons/logo_home.svg
  src/app/addepigram/page.tsx
  src/app/epigrams/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/search/page.tsx
  src/app/signup/page.tsx
  src/components/common/Header.tsx
  tailwind.config.ts
Labels: 🍀feat

#7 T1 18 text area solid outlined
  .vscode/extensions.json
  src/components/common/textAreaOutlined.tsx
  src/components/common/textareaSolid.tsx
Labels: 🍀feat

#11 T1 11 feat/card 수정
  public/assets/images/image_bg.png
  src/api/auth/userData.ts
  src/app/signup/page.tsx
  src/components/common/Card.tsx
  src/components/common/Card/Card.tsx
  src/components/common/Card/Tags.tsx
  src/components/common/Tags.tsx
  src/types/auth.ts
  src/types/card.ts
  src/types/sample.ts
Labels: 🛠fix

#13 T1 11 🎨 태그 컴포넌트 프롭 수정
  src/components/common/Tags.tsx
Labels: 🎯refact

#12 T1 30 landing page
  public/assets/icons/chevron_up.svg
  public/assets/icons/logo_epigram.svg
  public/assets/images/landing/img_Desktop_landing01.png
  public/assets/images/landing/img_Desktop_landing02.png
  public/assets/images/landing/img_Desktop_landing03.png
  public/assets/images/landing/img_Desktop_landing04.png
  public/assets/images/landing/img_Tablet_landing01.png
  public/assets/images/landing/img_Tablet_landing02.png
  public/assets/images/landing/img_Tablet_landing03.png
  public/assets/images/landing/img_Tablet_landing04.png
  public/assets/images/landing/img_mobile_landing01.png
  public/assets/images/landing/img_mobile_landing02.png
  public/assets/images/landing/img_mobile_landing03.png
  public/assets/images/landing/img_mobile_landing04.png
  public/assets/images/landing/img_zigzag.png
  src/app/globals.css
  src/app/page.tsx
  src/components/common/ButtonStart.tsx
  src/utils/landingImages.ts
  tailwind.config.ts
Labels: 🍀feat

#14 T1 38 main page
  package-lock.json
  package.json
  public/assets/images/angry.png
  public/assets/images/haapy.png
  public/assets/images/moved.png
  public/assets/images/plus.png
  public/assets/images/sad.png
  public/assets/images/scroll.png
  public/assets/images/worried.png
  src/api/client/AxiosInstance.tsx
  src/api/client/deleteComment.tsx
  src/api/client/editComment.tsx
  src/api/client/getNewCommentDatas.tsx
  src/api/client/getNewEpigramDatas.tsx
  src/api/client/todayEmotionPost.tsx
  src/api/server/getTodayEpigramData.tsx
  src/app/epigrams/page.tsx
  src/components/common/Card.tsx
  src/components/common/Comment.tsx
  src/components/common/Header.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/common/ProfileModal.tsx
  src/components/common/ScrollButton.tsx
  src/components/common/Tags.tsx
  src/components/epigramsPage/NewCommentList.tsx
  src/components/epigramsPage/NewEpigramList.tsx
  src/components/epigramsPage/TodayCard.tsx
  src/components/epigramsPage/TodayEmoji.tsx
  src/components/epigramsPage/TodayEmotion.tsx
  src/types/card.ts
  src/types/commentList.ts
  src/types/epigramList.ts
  src/types/profileModal.ts
  tsconfig.json
Labels: 🍀feat

#16 T1 31 search page
  src/api/getEpigrams.ts
  src/app/search/page.tsx
  src/components/common/Header.tsx
  src/components/common/SearchText.tsx
  src/components/common/Tags.tsx
  src/components/search/EpigramItem.tsx
  src/components/search/RecentSearches.tsx
  src/types/card.ts
  src/types/search.ts
  src/utils/highLightText.tsx
  tailwind.config.ts
Labels: 🍀feat

#17 T1 52 feed page
  src/api/client/getEpigrams.ts
  src/api/client/getNewFeedDatas.tsx
  src/app/feed/page.tsx
  src/app/search/page.tsx
  src/components/common/Header.tsx
  src/components/feedPage/FeedCard.tsx
  src/components/feedPage/FeedEpigramList.tsx
Labels: 🍀feat

#10 T1 22 Emotion Emoji & Calender
  .prettierrc
  package-lock.json
  package.json
  public/assets/icons/chevron_left.svg
  public/assets/icons/chevron_right.svg
  public/assets/icons/emotion/logo_angry.svg
  public/assets/icons/emotion/logo_heart.svg
  public/assets/icons/emotion/logo_sad.svg
  public/assets/icons/emotion/logo_smiling.svg
  public/assets/icons/emotion/logo_thinking.svg
  src/app/layout.tsx
  src/app/mypage/MyProfile.tsx
  src/app/page.tsx
  src/components/common/EmotionBoard.tsx
  src/components/common/EmotionCalender.tsx
  src/components/common/EmotionEmoji.tsx
  src/components/common/calendarCustom.css
  tailwind.config.ts
  tsconfig.json
Labels: 🍀feat

#19 T1 10 header navigation bar
  package-lock.json
  package.json
  src/api/auth/userData.ts
  src/api/client/getUserMe.ts
  src/app/layout.tsx
  src/app/login/oauth/GOOGLE/page.tsx
  src/app/login/oauth/KAKAO/page.tsx
  src/app/mypage/page.tsx
  src/app/search/page.tsx
  src/app/signup/oauth/google/page.tsx
  src/app/signup/oauth/kakao/page.tsx
  src/components/common/ButtonStart.tsx
  src/components/common/Header.tsx
  src/components/formField/LoginForm.tsx
  src/contexts/AuthContext.tsx
  src/hooks/useUserInfo.ts
Labels: 🎯refact

#21 T1 62 oauth
  .env
  next.config.mjs
  package-lock.json
  package.json
  src/api/auth/auth.ts
  src/api/auth/oauth.ts
  src/app/login/layout.tsx
  src/app/login/oauth/GOOGLE/page.tsx
  src/app/login/oauth/KAKAO/page.tsx
  src/app/page.tsx
  src/components/common/EmotionCalender.tsx
  src/components/common/EmotionEmoji.tsx
  src/components/formField/Buttons.tsx
  src/components/formField/FormField.tsx
  src/components/formField/LoginForm.tsx
  src/components/formField/OauthButtons.tsx
  src/components/formField/SignupForm.tsx
  src/components/formField/validation.ts
  src/middleware.ts
  src/types/auth.ts
  tsconfig.json
Labels: 🍀feat

#24 🐛 export 코드 추가
  next.config.mjs
Labels: 🛠fix

#22 T1 61 detail page
  next.config.mjs
  public/assets/icons/like.svg
  public/assets/icons/redlike.svg
  public/assets/images/move.png
  public/assets/images/toggle.png
  src/api/AxiosInstance.tsx
  src/api/client/addComment.tsx
  src/api/client/deleteEpigram.tsx
  src/api/client/getDetailCommentData.tsx
  src/api/client/getDetailData.tsx
  src/app/epigrams/[id]/page.tsx
  src/components/common/Comment.tsx
  src/components/common/ProfileModal.tsx
  src/components/detailPage/DetailCommentList.tsx
  src/components/detailPage/EpigramDetails.tsx
Labels: 🍀feat

#20 T1 33 epigram creat page
  src/api/client/Addepigramapi.tsx
  src/app/addepigram/page.tsx
  src/components/addepigram/AddEpigramPageInput.tsx
  src/components/common/textareaSolid.tsx
  src/utils/hashtag.tsx
Labels: 🍀feat

#25 T1 62 oauth
  .env
  src/api/auth/oauth.ts
  src/components/formField/OauthButtons.tsx
Labels: 🛠fix

#30 🐛 서버랜더링 오류, 동적라우팅으로 수정
  src/app/login/layout.tsx
  src/app/signup/layout.tsx
Labels: 🛠fix

#31 🐛 판별식 오류 수정
  src/components/formField/OauthButtons.tsx
Labels: 🛠fix

#34 T1 62 oauth 잘못된 hostname 변경
  src/api/auth/oauth.ts
  src/components/formField/OauthButtons.tsx
Labels: 🛠fix

#36 T1 60 간편로그인 - 구글 리다이렉트 주소 수정
  src/api/auth/oauth.ts
Labels: 🛠fix

#38 T1 31 search page
  src/app/search/page.tsx
  src/components/addepigram/AddEpigramPageInput.tsx
  src/components/common/Header.tsx
  src/components/search/RecentSearches.tsx
Labels: 🎯refact

#26 T1 42 my page
  next.config.mjs
  src/api/client/Addepigramapi.tsx
  src/api/client/getCalendarData.tsx
  src/api/client/getMyEmotion.tsx
  src/api/client/getUserCommentsDatas.tsx
  src/api/client/getUserEmotionBoard.tsx
  src/api/client/getUserEmotionCalender.tsx
  src/api/client/getUserEpigramDatas.tsx
  src/api/client/patchUserProfileUpdate.tsx
  src/api/client/postImgUpload.tsx
  src/api/client/updateUserProfile.tsx
  src/app/mypage/MyProfile.tsx
  src/app/mypage/page.tsx
  src/components/common/EmotionBoard.tsx
  src/components/common/EmotionCalender.tsx
  src/components/common/calendarCustom.css
  src/components/detailPage/DetailCommentList.tsx
  src/components/epigramsPage/TodayEmotion.tsx
  src/components/myPage/BottomList.tsx
  src/components/myPage/EmotionBoard.tsx
  src/components/myPage/EmotionCalender.tsx
  src/components/myPage/EmotionChart.tsx
  src/components/myPage/EmotionEmoji.tsx
  src/components/myPage/MyCommentList.tsx
  src/components/myPage/MyEpigramList.tsx
  src/components/myPage/MyProfile.tsx
  src/components/myPage/MyProfileModal.tsx
  src/components/myPage/calendarCustom.css
  src/components/myPage/updateProfileForm.tsx
Labels: 🍀feat, 🛠fix, 💎design
